quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Password09
quarkus.datasource.jdbc.url=jdbc::postgresql://localhost:54325/mydatabase?currentSchema=house_schema

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
